### ISSUE TITLE
Some stats about your project

### ISSUE THREAD

**Issue by gyachdav** [Rostlab/JS16_ProjectA#112]
Gringos, as part of the media blitz we're planning there will be a press release that will throw some big numbers at the readers. Can you provide some impressive statistics about the data your tools processed e.g. we assembled 10M data points by crawling through 5k pages describing 2k characters hundreds of houses, 5 continents etc.  Any thing that you think might be interesting IS interesting.

**Comment by gyachdav** [comment]
Status???? (next post will be with even more question marks :laughing: )

**Comment by ghost** [comment]
I will count the pages, that the scrapers are touching, and how many entries are stored in each collection :smile: 

But i would rather do that close to delivery time or are some numbers already required?

**Comment by sacdallago** [comment]
After FF is fine, focus on closing the things you are working on ;)

**Comment by ghost** [comment]
I can do that probably thursday. Otherwise Saturday/Sunday.
Probably you should assign someone else on this, @sacdallago ?
Basically it is just putting counter into the scraper and printing them out after the scraping. Or just looking into the final database and finding impressive numbers :stuck_out_tongue_closed_eyes:

**Comment by sacdallago** [comment]
Yes! :D so deffer, I'm on mobile so everything is shit. @kordianbruck how would you feel about doing this?

**Comment by togiberlin** [comment]
@gyachdav Can we close this issue? As far as I know, it's all here: https://www.got.show/statistics
