### ISSUE TITLE
Problem: Token

### ISSUE THREAD

**Issue by jcebel** [Rostlab/JS16_ProjectA#115]
Hey I've done something terribly wrong and I'm really sorry.
I've accidently pushed the token on github, as I was switching between two branches. I am really really sorry. I've deleted it as soon as I've seen my mistake. But as you can undo every change on github, it can always be found..
Can you please change it asap.
I'll help you with everything I can to clean this mess up.. I'm really sorry.

**Comment by ghost** [comment]
@kordianbruck

**Comment by sacdallago** [comment]
:D I can see @jonny3576 crying on his keyboard :D :D

**Comment by sacdallago** [comment]
Btw @kordianbruck I would kindly ask you to tear down your server at some stage... Just for the sake of testing.
Possibly after feature freeze, so that if people **MISTAKINGLY** hardcoded your API it can be changed before final deadline!.. And because at that stage it should be running on api.got.show

**Comment by kordianbruck** [comment]
Yea, my API won't be online for too much longer. Never mind that the token leaked somewhere ;D

@sacdallago is the production server set up yet? Then we can surely switch over and people will nag you with updating the code :smiling_imp:
