### ISSUE TITLE
House model

### ISSUE THREAD

**Issue by ghost** [Rostlab/JS16_ProjectA#13]
[House model](https://github.com/Rostlab/JS16_ProjectA/blob/master/app/models/house.js)

I fixed some problems there, but still some work is needed i am not sure about. 
_id as previously defined is not working. (No error with actual code, but no success when adding to collection either). An (pretty unreadable) id is set automatically by mongoose. Defining id as Number has the problem that, when adding a new data, the id has to be unique. This doesn´t happen automatically.

I don´t think that an array of characters should be in the model. Character n : 1 House relation. 
Current (? book, season ?) lord should reference to the character in the characters collection.

Needs revision.

**Comment by kordianbruck** [comment]
_id is the default PK assigned by MongoDB and it will always be that ugly string of characters. I would advise against using a custom number unless we directly fetch the PK ID from the wiki. Otherwise the Inserts will be really slow as we first have to run a query if the ID already exists - not the case with the default MongoDB way of doing it. If its only about relationships you should simply add an extra field in the House schema or an array in the document you are linking from. 

In terms of chacarcters: it would be better to add a field in the char table with the _id of the house if it really is a 1:n.

**Comment by theocheslerean** [comment]
We also have to model a schema for the houses types
