### ISSUE TITLE
Set up a document-oriented database (DB) + models

### ISSUE THREAD

**Issue by kordianbruck** [Rostlab/JS16_ProjectA#4]
- [x] Create all models

**Comment by togiberlin** [comment]
Somehow I can't assign more than one person on this task. However, let me announce here that I will be supporting docjag.

**Comment by sacdallago** [comment]
Issues are a one-to-one thing. You can though create issues that reference other issues and assign these to someone else.

The rationale behind is: Keep issues small! This issue is clearly too big and needs to be separated into different smaller ones like: "Create model for houses, references #4", aso.

P.S.: in this bigger issue you can use a checkbox list like the one @kordianbruck started referencing the child issues back, eg:
- [ ] Create model for houses: #xyz
- [ ] Create model for people: #zxy

**Comment by ghost** [comment]
I am closing this, since this issue is way too big. For parts of the db, create an issue if necessary.
