### ISSUE TITLE
Event scraper to do

### ISSUE THREAD

**Issue by theocheslerean** [Rostlab/JS16_ProjectA#46]

**Comment by theocheslerean** [comment]
Ages scraper done

**Comment by ghost** [comment]
Still to be scraped:
- [ ] Events

**Comment by ghost** [comment]
http://awoiaf.westeros.org/index.php/Timeline_of_major_events
To scrap automatically events from the wiki is very hard, because there are no such clear defined entities like events in the wiki. The table lines of the timeline seem to represent events. Problem here is that there is no consistent pattern of information representation and not every event has even a name (bold in the beginning of a cell). 

Not sure if we should scrap here something at all. A name and a date is probably not very helpful for the other projects...

**Comment by ghost** [comment]
@kordianbruck Please start the events filler. I needed to change the model a bit (name is not unique). Probably a re-index/re-start of mongoose is necessary.

**Comment by kordianbruck** [comment]
:checkered_flag: all done
