### ISSUE TITLE
Character DB contains cities

### ISSUE THREAD

**Issue by bandle** [Rostlab/JS16_ProjectA#69]
In the character DB there are cities present like:
King's Landing
Winterfell
Sunspear 
....

And also Donald Trump is still in the DB

**Comment by sacdallago** [comment]
> And also Donald Trump is still in the DB

Love it

**Comment by kordianbruck** [comment]
![download](https://cloud.githubusercontent.com/assets/298860/13779230/3f15815c-eaba-11e5-85de-843998b3d00c.jpg)

**Comment by theocheslerean** [comment]
Character collection had a couple of hours ago 6000 entries

**Comment by sacdallago** [comment]
@kordianbruck set up your server to use mongoLab instead of a local instance of mongodb please and provide R/W access only to people you trust, fine, but RO access to those that might want to have a look at the data.

We have a solution for the hosting now but I need to set it up properly and it's gonna take time.

Btw: see? You wanted to work on visualization, but there's so much else to take care of :dancer: 

P.S.: Are you happy with how the mentor(s) is/are now pushing more people to work together? I now fear turning on my car, maybe someone has put a bomb on it :boom: :D :D

**Comment by kordianbruck** [comment]
@theocheslerean the character collection has 2017 entrees: https://got-api.bruck.me/api/stats - thats the same that I have locally. 

@mbandle I removed donald and it now should be the exact result from the scraper. I can refill the database if we feel that there are things missing.

@sacdallago Will do - this is a separate issue tho ;)
Yea, its great! :+1:

**Comment by bandle** [comment]
The main problem isn't Donald Trump. 

When testing our search we found cities in the character-scraper - So cities are treated as characters:
These are also in the characters.json like:

```
{"name":"King's Landing","location":"Crownlands","government":"Feudal society","population":" 500,000 (approximately)","religion":"Faith of the Seven","founded":"2 BC","named for":"Aegon I Targaryen","notable places":"Red Keep","organizations":"Kingsguard"}
```

**Comment by ghost** [comment]
I am pretty sure, you just want to give us a hint on the error (what is very helpful =)), but let me mention, that the *.json files in wikiData shouldn´t be used by the other groups, because validation is later done by the filler.

Actually the filler deletes all properties, that do not match the model. Therefore when i get such a json by the scraper, the filler will remove all but not the property name and puts that in the db "mistakenly".
So, @theocheslerean, probably you can exclude these cities from the scraper? Otherwise i probably can find some "ugly" solutions to exclude them. (Check if typical city properties are in it, and skip that entry)

@mbandle Thank you for your report. We have a lot of data and can´t check on them manually. So, we are very happy that some checking on the other side of the api is taking place. =)

**Comment by bandle** [comment]
@theocheslerean Did you parse the wikis category information so far. I think this is possibly the easiest way to distinguish between locations and characters. Most of them have city, town or castle assigned.

**Comment by theocheslerean** [comment]
It was my mistake when i parsed for the names of the characters. Sorry guys. Will be fixed today

**Comment by sacdallago** [comment]
Hey guys, why don't you think about a "black list". Like a manually curated, community based list of things that don't need to get stored in particular places where the scraper cannot distinguish if something is right or wrong?
JUST in case you really can't solve these issues _just_ via logic / the wiki

**Comment by kordianbruck** [comment]
We now are down to 1949 characters with the new algorithm from @theocheslerean  - @mbandle please verify that you ain't getting any cities anymore. 

@sacdallago yea, a blacklist would work, but it should be the last option...

**Comment by kordianbruck** [comment]
Got the feedback from the other team that it is better now. Closing this issue for now.
