### ISSUE TITLE
API: mine tweets and combine with data from db

### ISSUE THREAD

**Issue by kordianbruck** [Rostlab/JS16_ProjectA#8]
To mine: https://twitter.com/search?q=Game%20of%20Thrones&src=tyah&lang=en
- [x] Create GET Twitter Stream by Keywords service
- [x] Add the function to stream multiple, real-time Tweets

**Comment by togiberlin** [comment]
@sacdallago How long should I let the web crawler run? 1, 2, 3 days?
What size in MByte is sufficient for our task?

**Comment by sacdallago** [comment]
@togiberlin you are talking about the Stream API right? Twitter also gives you access to the normal RESTapi. Stream API is only for live data, while you might want to work on historic data.
Integrating the StreamAPI makes sense if you want to create a stateful service with eg. a websocket so that the client can be updated with new data.

Hope I made myself clear, let me know otherwise!

**Comment by kordianbruck** [comment]
As per the information from google groups: we should definitely use an twitter client and implementation in JS. More information here:
- https://www.npmjs.com/package/twitter
- https://dev.twitter.com/rest/public

**Comment by togiberlin** [comment]
@sacdallago Got it. https://github.com/Rostlab/JS16_ProjectA/wiki/Get-Twitter-stream-by-keywords
P.S. I'll leave the webcrawler + readme-howto-file there if the following Projects B/C/D etc. decide to do some Text Mining on historic data.
