### ISSUE TITLE
Make fillers update entries

### ISSUE THREAD

**Issue by kordianbruck** [Rostlab/JS16_ProjectA#81]
instead of deleting the whole collection each time, we should instead simply update any entries who's data changed. This will enable other teams to add data to the DB and us updating the info from the Wiki.

We would need to run a intersect of the names in the db and the json to see which characters might have been deleted.

**Comment by sacdallago** [comment]
This sounds like something you want to do when the schemas are on a pre-release stage, something like after feature-freeze? Out of the scope of this seminar? But you can and are very welcome to continue to work on these projects after that, actually! VERY, WELCOME. But for now: first things first?

**Comment by ghost** [comment]
That´s nothing to me. BAM! 
It is really no big thing.
I will implement three policies:
1: Delete and refill
2: Update old entries and add new
3: Only add new entries/properties

**Comment by ghost** [comment]
@sacdallago @kordianbruck 
By the way, i don´t think that the snd policy (see above) makes sense in our case.
Following use-case:
- User saw wrong information.
- User updates the information via api.
- Filler is run. 
- Updated information is "updated" again by the filler to the old value/new value of the wiki.

Therefore, i think, it makes more sense to have one initial set of information and the wiki will never get scraped again for already existing entries. Only new ones will be added to the database. (see policy 3)

Because our automatic scraping will never be perfect, maybe it would make sense that our website at the end has a feature to do edits via a nice UI.

**Comment by ghost** [comment]
Well, everything is implemented ;)
Don´t forget to update the cfg file. See template.

**Comment by sacdallago** [comment]
Good @Adiolis 
You are right about information overwriting, this is indeed an issue. There's a trade off in either solution, as in general it would be nice if people contributed more to the wiki, rather than updating data via API (because that way _everyone_ using the API will have the latest data). Which data is updated via API anyway? Is this like _happening_ often? Maybe it makes sense to **not** implement this possibility for the data that is scraped?   

I honestly have no one take on this, I leave this up to you!    

@yashha & project F in general: can you make it very, very clear somewhere on the webpage that the more people contribute to the (media)wiki, the better the data will be for those who scrape the wiki the first time?

**Comment by kordianbruck** [comment]
@sacdallago only one team requested the API token till now, so I'm not sure anyone actually pushes data to the API.

**Comment by sacdallago** [comment]
@kordianbruck so how about we cross this of the list? No possibility to update data **that is scraped**. The rest, might as well

**Comment by kordianbruck** [comment]
@sacdallago you mean over the API? Yea, makes sense - originally we thought that we would have other teams add information to the datasets over the API. So you vote to remove all functions that update scraped data from the API? Yes?

**Comment by sacdallago** [comment]
Yes, I would upvote that. Let me take care of this somewhere else, wait.
