### ISSUE TITLE
API for returning top-rankings of PLOD

### ISSUE THREAD

**Issue by mammuth** [Rostlab/JS16_ProjectA#84]
Project B seems to put their PLOD-data to your database (https://github.com/Rostlab/JS16_ProjectB_Group7/issues/5#event-593684802).

We would need an API to get an array of characters with the highest PLOD, so we can show a section on the page "Most likely to die soon" with the eg. TOP3 characters (Eddard, Jeoffry, Jon)

**Comment by togiberlin** [comment]
@mammuth Isn't the PLOD of every human 100% :D
...I assume you mean with soon --> within season 6.

**Comment by kordianbruck** [comment]
@mammuth we will have two PLOD values, which one do you want it ranked by or do you want to have the top10 from both?

**Comment by mammuth** [comment]
Äh, are those two fields from the two different plod groups? 

I'm afraid we need to show both ;-) 

Btw, There seems to be some discussion on the other issue if I'm right, about how to filter out "bad results" and some other stuff.

**Comment by sacdallago** [comment]
I confirm: we are trying to see if we can port some centrality measures back to A so that from the data itself you can generate classifications on which characters are important. It's actually a pretty damn easy thing to do with [the right package](https://www.npmjs.com/package/ngraph.centrality) and by just scraping of all pages in the wiki, creating different graphs for different types of data (chars, houses, blabla) and putting the links via the package linked before: BOOM, you have an intuitive importance measure.
This can then be used for filtering, aka: most important characters, most important houses, most important whatever.

Explore the possibility if you can and ask the PLOD guys to give you a hand with this one

**Comment by sacdallago** [comment]
P.S.: yes @mammuth , you need to show both because averaging over ML devices is like averaging over bananas and apples :laughing:

**Comment by sacdallago** [comment]
P.P.S.: Maybe ask what these guys are doing? https://github.com/Rostlab/JS16_ProjectB_Group6/pull/48/files

But if I'm not mistaken they are generating these popularity indexes upon data generated by @gyachdav which is kind of old.. and the _page rank_ that Guy was implementing was in a beta-state... Would be nice if the graph and the centrality measurement could be run periodically

**Comment by gyachdav** [comment]
Indeed the "pageRank" calculations needs to be refreshed periodically.

**Comment by gyachdav** [comment]
I know Jonas katnebach from one of the Ds got my script and data to run the beta version of the pageRank. I also know that the ML groups are also working on implementing page rank. This seems to become a central measure to many groups so I suggest we just add members from all these groups into this issue and have the first group that implement a solid page rank populate the db with this measure. 

@Sacdallago please add those members here and let them know we want the pageRank measure in the DB. As mentioned before I'm posting from a crappy GitHub app on my phone while on a plane going through choppy weather (ok fine TMI but if you don't hear any more from me then call the authorities  :p) and cannot properly reference shit from here.

**Comment by gyachdav** [comment]
Actually @sacdallago just open a new issue for that here.

**Comment by sacdallago** [comment]
@gyachdav OK
As for this issue itself: The API doesn't have to return a classification, you can sort the results of the APi call yourselves for the time being @mammuth . Thus; closing.
